From python:3.7-slim
#From alpine:3.2
Label maintainer = 'neeraj@realbooks.in'

WORKDIR /usr/src/app

COPY Pipfile ./
RUN apt-get update && apt-get install -y git mariadb-client python3-dev libmariadbclient-dev build-essential
RUN pip install pipenv
RUN pipenv install

ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone